src/main/java/com/safira/steamapp/domain/Game.java
package com.safira.steamapp.domain;

import com.safira.steamapp.service.HTTPRequester;

import javax.persistence.*;
import java.io.Serializable;
import java.text.DecimalFormat;
import java.util.Comparator;

/**
 * Created by developer on 30/01/15.
 */

@Entity
@Table(name = "GAMES")
public class Game implements Comparable<Game>, Serializable {

    @Id
    @Column(name="GAME_ID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    @Column(name="GAME_APP_ID")
    private String appid;

    @Column(name="GAME_NAME")
    private String name;

    @Column(name="GAME_PLAY_TIME")
    private String playTime;

    @Column(name="GAME_ICON_URL")
    private String iconURL;

    @Column(name="GAME_LOGO_URL")
    private String logoURL;

    @ManyToOne
    private Player owner;

    public void setOwner(Player owner) {
        this.owner = owner;
    }

    public Player getOwner() {
        return owner;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public void setAppid(String appid) {
        this.appid = appid;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setPlayTime(String playTime) {
        this.playTime = playTime;
    }

    public void setIconURL(String iconURL) {
        this.iconURL = iconURL;
    }

    public void setLogoURL(String logoURL) {
        this.logoURL = logoURL;
    }

    // Default Constructor
    public Game(){}

    public Game(String appid, String name, String playTime, String iconHash, String logoHash){
        HTTPRequester http = new HTTPRequester();

        this.appid = appid;
        this.name = name;
        this.playTime = playTime;
        this.iconURL = http.getImage(iconHash, appid);
        this.logoURL = http.getImage(logoHash, appid);
    }

    public String getAppid() {
        return appid;
    }

    public String getName() {
        return name;
    }

    @Override
    public int compareTo(Game o) {
        return 0;
    }

    public static Comparator<Game> GameNameComparator = new Comparator<Game>() {
        public int compare(Game game1, Game game2) {
            String gameName1 = game1.getName().toUpperCase();
            String gameName2 = game2.getName().toUpperCase();

            return gameName1.compareTo(gameName2);
        }
    };

    public String getPlayTime() {
        return playTime;
    }

    public String getIconURL() {
        return iconURL;
    }

    public String getLogoURL() {
        return logoURL;
    }

    public String getPlayedHours() {

        Double hoursPlayed = Double.parseDouble(playTime)/60;
        return new DecimalFormat("#.#").format(hoursPlayed);

    }
}

src/main/webapp/WEB-INF/views/friend.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<c:url var="recentlyPlayed_url"  value="/recentlyPlayed" />
<html>
  <head>
    <%@ include file="/WEB-INF/views/includeHead.jsp" %>
  </head>
  <body>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="row">
              <div class="col-sm-12">
                <h1 class="text-center">Friend</h1>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-4">
                <p>
                  <img class="img img-thumbnail img-responsive" src="${friend.avatarFullURL}"/>
                </p>
              </div>
              <div class="col-sm-8">
                <p><strong>Steam ID 64 bit:</strong>  ${friend.steamID64}</p>
                <p><strong>Nick name:</strong>  ${friend.personalName}</p>
                <p><strong>Real name:</strong>  ${friend.realName}</p>
                <p class="text-center">
                  <a class="btn btn-default" href="${friend.profileURL}">Go to Profile</a>
                  <a class="btn btn-default" href="${recentlyPlayed_url}?steamID64=${friend.steamID64}">Recently Played</a>
                </p>
              </div>
            </div>
             <div class="row">
               <div class="col-sm-12">
                  <p class="text-center"><button class="btn btn-default" onclick="window.history.back()">Back</button></p>
               </div>
             </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </body>
</html>

src/main/webapp/WEB-INF/views/friendList.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<c:url var="friend_url"  value="/friend" />
<html>
  <head>
    <%@ include file="/WEB-INF/views/includeHead.jsp" %>
  </head>
  <body>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
          <div class="panel-body">
            <h1 class="text-center">These are your friends</h1>
            <p class="text-center"><button class="btn btn-default" onclick="window.history.back()">Back</button></p>
              <table class="table table-hover">
              <c:forEach var="friend" items="${friends}">
              <tr><td>
              <a href="${friend_url}?steamID64=${friend.steamID64}">${friend.personalName}
              </td></tr>
              </c:forEach>
              </table>
              <p class="text-center"><button class="btn btn-default" onclick="window.history.back()">Back</button></p>
          </div>
        </div>
      </div>
    </div>
  </div>
  </body>
</html>

src/main/webapp/WEB-INF/views/game.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<c:url var="news_url"  value="/news" />
<html>
  <head>
    <%@ include file="/WEB-INF/views/includeHead.jsp" %>
  </head>
  <body>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-body panel-default">
          <div class="row">
            <div class="col-sm-12">
              <h1 class="text-center">Game</h1>
            </div>
          </div>
            <div class="row">
              <div class="col-sm-4">
                <p class="text-center">
                  <img class="img img-thumbnail img-responsive" src="${game.logoURL}"/>
                </p>
                <p class="text-center">
                  <a href="${news_url}?appid=${game.appid}" class="btn btn-default">News</a>
                </p>
              </div>
              <div class="col-sm-8">
                <p>
                   <strong>Game Name:</strong> <c:out value="${game.name}"/>
                 </p>
                <p>
                   <strong>Store link: </strong> <a href="http://store.steampowered.com/app/<c:out value='${game.appid}'/>">http://store.steampowered.com/app/<c:out value='${game.appid}'/></a>
                 </p>
                <p>
                   <strong>Steam Application ID:</strong> <c:out value="${game.appid}"/>
                 </p>
                <p>
                  <strong>Hours Played:</strong> <c:out value="${game.playedHours}"/> hs
                </p>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-12">
                <p class="text-center"><button class="btn btn-default" onclick="window.history.back()">Back</button></p>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
  </body>
</html>

src/main/webapp/WEB-INF/views/gameList.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<c:url var="game_url"  value="/game" />
<c:url var="home_url"  value="/home" />
<c:url var="updateGameData_url"  value="/updateGameData" />
<html>
  <head>
    <%@ include file="/WEB-INF/views/includeHead.jsp" %>
  </head>
  <body>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-body panel-default">
          <h1 class="text-center">These are your games</h1>
            <p class="text-center"><a class="btn btn-default" href="${home_url}">Back</a></p>
            <p class="text-center"><a class="btn btn-default" href="${updateGameData_url}">Update Game Data</a></p>
            <table class="table table-hover">
              <tr><th>Game</th></tr>
              <c:forEach var="game" items="${gameList}">
                <tr><td>
                  <a href="${game_url}?appid=${game.appid}">${game.name}</a>
                </td></tr>
              </c:forEach>
          </table>
          <p class="text-center"><a class="btn btn-default" href="${home_url}">Back</a></p>
        </div>
      </div>
    </div>
  </div>
  </body>
</html>

src/main/webapp/WEB-INF/views/home.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>



<html>
  <head>
    <%@ include file="/WEB-INF/views/includeHead.jsp" %>
  </head>
  <body>
    <div class="container">
    	<div class="row">
    		<div class="col-md-6 col-md-offset-3">
    			<div class="panel panel-body panel-default">
    				<h1 class="text-center">Please insert your username</h1>
    				
    				<spring:hasBindErrors name="vanityNameForm">
    				        <c:forEach var="error" items="${errors.allErrors}">
    				           <div class="alert alert-danger alert-dismissible" role="alert">
    				                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    				           		<strong>Oops! </strong><spring:message code="${error.code}"/>
    				           </div>
    				        </c:forEach>
    				</spring:hasBindErrors>
    				
    				<c:url var="home_url" value="/home" />
    				<form:form action="${home_url}" method="POST" modelAttribute="vanityNameForm">
    				    <div class="form-group">
    				        <form:label path="Nickname">Nickname</form:label>
    				        <div class="input-group">
                                <form:input path="Nickname" cssClass="form-control" autofocus="autofocus"></form:input>
                                <span class="input-group-btn">
                                    <input type="submit" value="Submit" class="btn btn-primary"/>
                                </span>
                            </div>
                        </div>
    				</form:form>
    			</div>
    		</div>
    	</div>
    </div>
  </body>
</html>

src/main/webapp/WEB-INF/views/includeHead.jsp
<title>Steam App</title>
<link rel="icon" type="image/png" href="<c:url value='/resources/imgs/icon.png'/>">
<link href='https://fonts.googleapis.com/css?family=Signika:400,700' rel='stylesheet' type='text/css'>
<link href="<c:url value='/resources/css/bootstrap.min.css'/>" rel="stylesheet">
<link href="<c:url value='/resources/css/main.css'/>" rel="stylesheet">
<script src="<c:url value='/resources/js/jquery.min.js'/>"></script>
<script src="<c:url value='/resources/js/bootstrap.min.js'/>"></script>

src/main/webapp/WEB-INF/views/news.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>

<html>
  <head>
    <%@ include file="/WEB-INF/views/includeHead.jsp" %>
  </head>
  <body>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-body">
              <h1 class="text-center">News</h1>
              <p class="text-center"><button class="btn btn-default" onclick="window.history.back()">Back</button></p>
              <c:forEach var="newItem" items="${news}">
                <div class="col-md-12">
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <h3 class="panel-title"><a href="${newItem.url}">${newItem.title}</a></h3>
                    </div>
                    <div class="panel-body">
                      <p>${newItem.contents}</p>
                    </div>
                    <div class="panel-footer">
                      <p><span class="pull-left"><fmt:formatDate value="${newItem.date}" pattern="yyyy-MM-dd"/></span>
                      <span class="pull-right"><em>by: </em>${newItem.author}</span></p>
                    </div>
                  </div>
                </div>
              </c:forEach>

              <p class="text-center"><button class="btn btn-default" onclick="window.history.back()">Back</button></p>

            </div>
        </div>
      </div>
    </div>
  </div>
  </body>
</html>

src/main/webapp/WEB-INF/views/recentlyPlayed.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<c:url var="game_url"  value="/game" />
<html>
  <head>
    <%@ include file="/WEB-INF/views/includeHead.jsp" %>
  </head>
  <body>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-body panel-default">
          <h1 class="text-center">Recently Played Games</h1>
            <p class="text-center"><button class="btn btn-default" onclick="window.history.back()">Back</button></p>
            <table class="table table-hover">
              <tr><th>Game</th></tr>
              <c:forEach var="game" items="${games}">
                <tr><td>
                  <a href="${game_url}?appid=${game.appid}">${game.name}</a>
                </td></tr>
              </c:forEach>
          </table>
          <p class="text-center"><button class="btn btn-default" onclick="window.history.back()">Back</button></p>
        </div>
      </div>
    </div>
  </div>
  </body>
</html>

src/main/webapp/WEB-INF/views/user.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<c:url var="gameList_url"  value="/gameList" />
<c:url var="friendList_url"  value="/friendList" />
<c:url var="userInfo_url"  value="/userInfo" />
<c:url var="recentlyPlayed_url"  value="/recentlyPlayed" />
<c:url var="updateData_url"  value="/updateData" />
<c:url var="quit_url"  value="/quit" />
<html>
  <head>
    <%@ include file="/WEB-INF/views/includeHead.jsp" %>
  </head>
  <body>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-body panel-default">
          <h1 class="text-center">Menu</h1>
            <spring:hasBindErrors name="errors">
            <c:forEach var="error" items="${errors.errors}">
                            <div class="alert alert-danger alert-dismissible" role="alert">
                              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                              <c:out value="${error.value}"/>
                            </div>
            </c:forEach>
            </spring:hasBindErrors>

            <div class="main-menu">
                <p class="text-center">
                  <a href="${gameList_url}" class="btn btn-default text-center">Games List</a>
                </p>
                <p class="text-center">
                  <a href="${friendList_url}" class="btn btn-default text-center">Friends</a>
                </p>
                <p class="text-center">
                  <a href="${userInfo_url}" class="btn btn-default text-center">${steamUser.vanity}</a>
                </p>
                <p class="text-center">
                  <a href="${recentlyPlayed_url}" class="btn btn-default text-center">Recently Played</a>
                </p>
                <p class="text-center">
                  <a href="${updateData_url}" class="btn btn-default text-center">Update User Data</a>
                </p>
                <p class="text-center">
                  <a href="${quit_url}" class="btn btn-danger text-center">Quit</a>
                </p>
            </div>
        </div>
      </div>
    </div>
  </div>
  </body>
</html>

src/main/webapp/WEB-INF/views/userInfo.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<html>
  <head>
    <%@ include file="/WEB-INF/views/includeHead.jsp" %>
  </head>
  <body>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="row">
              <div class="col-sm-12">
                <h1 class="text-center">Profile</h1>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-4">
                <p>
                  <img class="img img-thumbnail img-responsive" src="${steamUser.user.avatarFullURL}"/>
                </p>
              </div>
              <div class="col-sm-8">
                <p><strong>Steam ID 64 bit:</strong>  ${steamUser.user.steamID64}</p>
                <p><strong>Nick name:</strong>  ${steamUser.user.personalName}</p>
                <p><strong>Real name:</strong>  ${steamUser.user.realName}</p>
                <p class="text-center">
                  <a class="btn btn-default" href="${steamUser.user.profileURL}">Go to Profile</a>
                </p>
              </div>
            </div>
             <div class="row">
               <div class="col-sm-12">
                  <p class="text-center"><button class="btn btn-default" onclick="window.history.back()">Back</button></p>
               </div>
             </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </body>
</html>